#!/bin/bash
cd "$( dirname "${BASH_SOURCE[0]}")"
export BLUE='\033[1;94m'
export RED='\033[1;91m'

title="$RED 		Hi BRO!) it's ssh2tun \n"
prompt=
options=("SSH->System" "SSH->namespace" "SSH->System->namespace" "SSH->namespace->Wi-Fi" "SSH->System->namespace->Wi-Fi" "Settings")

clear
echo -e -n  "$title"
PS3="$prompt "
select opt in "${options[@]}" "Quit"; do 

    case "$REPLY" in

    1 ) clear
		echo -e -n "$BLUE SSH->System \n"
		src/sshON_sys
		clear
		src/sshOFF_sys
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
	2 ) clear
		echo -e -n "$BLUE SSH->namespace \n"
		src/sshON_name
		clear
		src/sshOFF_name
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
	3 ) clear
		echo -e -n "$BLUE SSH->System->namespace \n"
		src/sshON_name_sys
		clear
		src/sshOFF_name_sys
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
	4 ) clear
		echo -e -n "$BLUE SSH->namespace->Wi-Fi \n"
		src/sshON_name_wifi 
		clear
		src/sshOFF_name_wifi
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
	5 ) clear
		echo -e -n "$BLUE SSH->System->namespace->Wi-Fi \n"
		src/sshON_name_sys_wifi 
		clear
		src/sshOFF_name_sys_wifi 
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
    6 ) clear
		echo -e -n "$BLUE Settings \n"
		src/settings
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;

    $(( ${#options[@]}+1 )) ) clear; break;;
    *) echo -e -n  "$RED Invalid option. Try another one. \n";continue;;

    esac

done
