#!/bin/bash
cd "$( dirname "${BASH_SOURCE[0]}")"
set -x

remote_ip=$(sed '2!d' variables.conf)
remote_port=$(sed '3!d' variables.conf)
bind_iface=$(sed '8!d' variables.conf)
bad_tun=$(sed '9!d' variables.conf)
local_ip=$(sed '6!d' variables.conf)
bind_port=$(sed '7!d' variables.conf)


id="$RANDOM"
local_server="$local_ip:$bind_port"
pwd | cat > /tmp/dist
dist=$(cat /tmp/dist)
sudo iptables-save > /tmp/iptables.conf
ls /dev/pts/ | cat > /tmp/sshttyold && xfce4-terminal --geometry=62x24 --hide-scrollbar --hide-toolbar && ls /dev/pts/ | cat > /tmp/sshttynew && grep -vf /tmp/sshttyold /tmp/sshttynew | sort -u > /tmp/sshtty
ssh_start=$(sed '1!d' /tmp/sshtty)
sudo ./ttyecho -n /dev/pts/$ssh_start ./startSSH
sleep 3
sudo ip tuntap add dev $bad_tun mode tun
sudo ip link set $bad_tun up
sudo ip link set dev $bad_tun up mtu 1500
sudo ip addr add 10.0.0.1/30 dev $bad_tun
sudo ip addr add dev $bad_tun local 10.9.3.18 peer 10.9.3.17
sudo ip route add 10.9.0.1/32 via 10.9.3.17
sudo sysctl -w net.ipv4.conf.$bad_tun.forwarding=1
sudo ip rule add fwmark $id lookup $id
sudo ip route add default via 10.0.0.2 table $id
sudo iptables -t mangle -I PREROUTING -i $bind_iface -p tcp -j MARK --set-mark $id

xfce4-terminal --geometry=62x24 --hide-scrollbar --hide-toolbar --hide-borders --working-directory=$dist -e "./nameON"

sudo ./badvpn-tun2socks --tundev $bad_tun --netif-ipaddr 10.0.0.2 --netif-netmask 255.255.255.0 --socks-server-addr $local_server
